theme: jekyll-theme-cayman
title: HKUST-DNN
description: State-level COVID-19 Trend Forecasting using Deep Neural Networks
show_downloads: false
google_analytics: G-DDFGPDH5TE
github:
  is_project_page: false
updated_on: 2021-06-21
model_date: 2021-06-19
